version: '2.3'

services:

  nsq:
    image: nsqio/nsq
    restart: always
    ports:
      - 4151:4151
      - 4150:4150
    volumes:
      - ./keys:/keys
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --tls-cert /keys/cert.pem --tls-key /keys/key.pem
    depends_on:
      - nsqlookupd

  nsqlookupd:
    image: nsqio/nsq
    restart: always
    ports:
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd

  nsqadmin:
    image: nsqio/nsq
    restart: always
    ports:
      - 4171:4171
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd

  dev:
    image: rust
    working_dir: "/app"
    user: "${UID}:${GID}"
    volumes:
      - .:/app:rw
